package bean;
// Generated 30/11/2023 16:17:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompraRal generated by hbm2java
 */
@Entity
@Table(name="compra_ral"
    ,catalog="db_rodrigo_ledesma"
)
public class CompraRal  implements java.io.Serializable {


     private int idcompraRal;
     private FornecedorRal fornecedorRal;
     private FuncionarioRal funcionarioRal;
     private Date dataCompraRal;
     private double compraTotalRal;
     private String notaFiscalRal;
     

    public CompraRal() {
    }

	
    public CompraRal(int idcompraRal, FornecedorRal fornecedorRal, FuncionarioRal funcionarioRal, Date dataCompraRal, double compraTotalRal) {
        this.idcompraRal = idcompraRal;
        this.fornecedorRal = fornecedorRal;
        this.funcionarioRal = funcionarioRal;
        this.dataCompraRal = dataCompraRal;
        this.compraTotalRal = compraTotalRal;
    }
    public CompraRal(int idcompraRal, FornecedorRal fornecedorRal, FuncionarioRal funcionarioRal, Date dataCompraRal, double compraTotalRal, String notaFiscalRal, Set compraProdutoRals) {
       this.idcompraRal = idcompraRal;
       this.fornecedorRal = fornecedorRal;
       this.funcionarioRal = funcionarioRal;
       this.dataCompraRal = dataCompraRal;
       this.compraTotalRal = compraTotalRal;
       this.notaFiscalRal = notaFiscalRal;
       
    }
   
     @Id 

    
    @Column(name="idcompra_ral", unique=true, nullable=false)
    public int getIdcompraRal() {
        return this.idcompraRal;
    }
    
    public void setIdcompraRal(int idcompraRal) {
        this.idcompraRal = idcompraRal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_fornecedor_ral", nullable=false)
    public FornecedorRal getFornecedorRal() {
        return this.fornecedorRal;
    }
    
    public void setFornecedorRal(FornecedorRal fornecedorRal) {
        this.fornecedorRal = fornecedorRal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_funcionario_ral", nullable=false)
    public FuncionarioRal getFuncionarioRal() {
        return this.funcionarioRal;
    }
    
    public void setFuncionarioRal(FuncionarioRal funcionarioRal) {
        this.funcionarioRal = funcionarioRal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataCompra_ral", nullable=false, length=10)
    public Date getDataCompraRal() {
        return this.dataCompraRal;
    }
    
    public void setDataCompraRal(Date dataCompraRal) {
        this.dataCompraRal = dataCompraRal;
    }

    
    @Column(name="compraTotal_ral", nullable=false, precision=10)
    public double getCompraTotalRal() {
        return this.compraTotalRal;
    }
    
    public void setCompraTotalRal(double compraTotalRal) {
        this.compraTotalRal = compraTotalRal;
    }

    
    @Column(name="notaFiscal_ral", length=50)
    public String getNotaFiscalRal() {
        return this.notaFiscalRal;
    }
    
    public void setNotaFiscalRal(String notaFiscalRal) {
        this.notaFiscalRal = notaFiscalRal;
    }





}


