package bean;
// Generated 30/11/2023 16:17:26 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FornecedorRal generated by hbm2java
 */
@Entity
@Table(name="fornecedor_ral"
    ,catalog="db_rodrigo_ledesma"
)
public class FornecedorRal  implements java.io.Serializable {


     private int idfornecedorRal;
     private String nomeRal;
     private String apelidoRal;
     private String enderecoRal;
     private String cepRal;
     private String cidadeRal;
     private String complementoRal;
     private String telefoneRal;
     private String emailRal;
     private String cpfRal;
     private String rgRal;
     private Date dataNascimentoRal;
     private String nomeContaBancRal;
     private String numAgenciaBancRal;
     private String numContaBancRal;
   

    public FornecedorRal() {
    }

	
    public FornecedorRal(int idfornecedorRal, String nomeRal, String apelidoRal, String enderecoRal, String cepRal, String cidadeRal, String complementoRal, String telefoneRal, String emailRal, String cpfRal, String rgRal, Date dataNascimentoRal, String nomeContaBancRal, String numAgenciaBancRal, String numContaBancRal) {
        this.idfornecedorRal = idfornecedorRal;
        this.nomeRal = nomeRal;
        this.apelidoRal = apelidoRal;
        this.enderecoRal = enderecoRal;
        this.cepRal = cepRal;
        this.cidadeRal = cidadeRal;
        this.complementoRal = complementoRal;
        this.telefoneRal = telefoneRal;
        this.emailRal = emailRal;
        this.cpfRal = cpfRal;
        this.rgRal = rgRal;
        this.dataNascimentoRal = dataNascimentoRal;
        this.nomeContaBancRal = nomeContaBancRal;
        this.numAgenciaBancRal = numAgenciaBancRal;
        this.numContaBancRal = numContaBancRal;
    }
    public FornecedorRal(int idfornecedorRal, String nomeRal, String apelidoRal, String enderecoRal, String cepRal, String cidadeRal, String complementoRal, String telefoneRal, String emailRal, String cpfRal, String rgRal, Date dataNascimentoRal, String nomeContaBancRal, String numAgenciaBancRal, String numContaBancRal, Set compraRals) {
       this.idfornecedorRal = idfornecedorRal;
       this.nomeRal = nomeRal;
       this.apelidoRal = apelidoRal;
       this.enderecoRal = enderecoRal;
       this.cepRal = cepRal;
       this.cidadeRal = cidadeRal;
       this.complementoRal = complementoRal;
       this.telefoneRal = telefoneRal;
       this.emailRal = emailRal;
       this.cpfRal = cpfRal;
       this.rgRal = rgRal;
       this.dataNascimentoRal = dataNascimentoRal;
       this.nomeContaBancRal = nomeContaBancRal;
       this.numAgenciaBancRal = numAgenciaBancRal;
       this.numContaBancRal = numContaBancRal;
      
    }
   
     @Id 

    
    @Column(name="idfornecedor_ral", unique=true, nullable=false)
    public int getIdfornecedorRal() {
        return this.idfornecedorRal;
    }
    
    public void setIdfornecedorRal(int idfornecedorRal) {
        this.idfornecedorRal = idfornecedorRal;
    }

    
    @Column(name="nome_ral", nullable=false, length=45)
    public String getNomeRal() {
        return this.nomeRal;
    }
    
    public void setNomeRal(String nomeRal) {
        this.nomeRal = nomeRal;
    }

    
    @Column(name="apelido_ral", nullable=false, length=45)
    public String getApelidoRal() {
        return this.apelidoRal;
    }
    
    public void setApelidoRal(String apelidoRal) {
        this.apelidoRal = apelidoRal;
    }

    
    @Column(name="endereco_ral", nullable=false, length=80)
    public String getEnderecoRal() {
        return this.enderecoRal;
    }
    
    public void setEnderecoRal(String enderecoRal) {
        this.enderecoRal = enderecoRal;
    }

    
    @Column(name="cep_ral", nullable=false, length=80)
    public String getCepRal() {
        return this.cepRal;
    }
    
    public void setCepRal(String cepRal) {
        this.cepRal = cepRal;
    }

    
    @Column(name="cidade_ral", nullable=false, length=45)
    public String getCidadeRal() {
        return this.cidadeRal;
    }
    
    public void setCidadeRal(String cidadeRal) {
        this.cidadeRal = cidadeRal;
    }

    
    @Column(name="complemento_ral", nullable=false, length=50)
    public String getComplementoRal() {
        return this.complementoRal;
    }
    
    public void setComplementoRal(String complementoRal) {
        this.complementoRal = complementoRal;
    }

    
    @Column(name="telefone_ral", nullable=false, length=14)
    public String getTelefoneRal() {
        return this.telefoneRal;
    }
    
    public void setTelefoneRal(String telefoneRal) {
        this.telefoneRal = telefoneRal;
    }

    
    @Column(name="email_ral", nullable=false, length=80)
    public String getEmailRal() {
        return this.emailRal;
    }
    
    public void setEmailRal(String emailRal) {
        this.emailRal = emailRal;
    }

    
    @Column(name="cpf_ral", nullable=false, length=14)
    public String getCpfRal() {
        return this.cpfRal;
    }
    
    public void setCpfRal(String cpfRal) {
        this.cpfRal = cpfRal;
    }

    
    @Column(name="rg_ral", nullable=false, length=15)
    public String getRgRal() {
        return this.rgRal;
    }
    
    public void setRgRal(String rgRal) {
        this.rgRal = rgRal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_ral", nullable=false, length=10)
    public Date getDataNascimentoRal() {
        return this.dataNascimentoRal;
    }
    
    public void setDataNascimentoRal(Date dataNascimentoRal) {
        this.dataNascimentoRal = dataNascimentoRal;
    }

    
    @Column(name="nomeContaBanc_ral", nullable=false, length=50)
    public String getNomeContaBancRal() {
        return this.nomeContaBancRal;
    }
    
    public void setNomeContaBancRal(String nomeContaBancRal) {
        this.nomeContaBancRal = nomeContaBancRal;
    }

    
    @Column(name="numAgenciaBanc_ral", nullable=false, length=15)
    public String getNumAgenciaBancRal() {
        return this.numAgenciaBancRal;
    }
    
    public void setNumAgenciaBancRal(String numAgenciaBancRal) {
        this.numAgenciaBancRal = numAgenciaBancRal;
    }

    
    @Column(name="numContaBanc_ral", nullable=false, length=10)
    public String getNumContaBancRal() {
        return this.numContaBancRal;
    }
    
    public void setNumContaBancRal(String numContaBancRal) {
        this.numContaBancRal = numContaBancRal;
    }


@Override
public String toString(){
    return getNomeRal();
}

@Override
public boolean equals(Object object){
    if(object instanceof FornecedorRal){
        FornecedorRal produtos = (FornecedorRal) object;
        if(this.getIdfornecedorRal() == produtos.getIdfornecedorRal()){
            return true;
        }
    }
    return false;
}

}


