package bean;
// Generated 19/10/2023 12:07:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompraRal generated by hbm2java
 */
@Entity
@Table(name="compra_ral"
    ,catalog="db_rodrigo_ledesma"
)
public class CompraRal  implements java.io.Serializable {


     private int idcompraRal;
     private FornecedorRal fornecedorRal;
     private FuncionarioRal funcionarioRal;
     private String dataCompraRal;
     private int totalRal;
    

    public CompraRal() {
    }

	
    public CompraRal(int idcompraRal, FornecedorRal fornecedorRal, FuncionarioRal funcionarioRal, String dataCompraRal, int totalRal) {
        this.idcompraRal = idcompraRal;
        this.fornecedorRal = fornecedorRal;
        this.funcionarioRal = funcionarioRal;
        this.dataCompraRal = dataCompraRal;
        this.totalRal = totalRal;
    }
    public CompraRal(int idcompraRal, FornecedorRal fornecedorRal, FuncionarioRal funcionarioRal, String dataCompraRal, int totalRal, Set compraProdutoRals) {
       this.idcompraRal = idcompraRal;
       this.fornecedorRal = fornecedorRal;
       this.funcionarioRal = funcionarioRal;
       this.dataCompraRal = dataCompraRal;
       this.totalRal = totalRal;
     
    }
   
     @Id 

    
    @Column(name="idcompra_ral", unique=true, nullable=false)
    public int getIdcompraRal() {
        return this.idcompraRal;
    }
    
    public void setIdcompraRal(int idcompraRal) {
        this.idcompraRal = idcompraRal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_fornecedor_ral", nullable=false)
    public FornecedorRal getFornecedorRal() {
        return this.fornecedorRal;
    }
    
    public void setFornecedorRal(FornecedorRal fornecedorRal) {
        this.fornecedorRal = fornecedorRal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_funcionario_ral", nullable=false)
    public FuncionarioRal getFuncionarioRal() {
        return this.funcionarioRal;
    }
    
    public void setFuncionarioRal(FuncionarioRal funcionarioRal) {
        this.funcionarioRal = funcionarioRal;
    }

    
    @Column(name="dataCompra_ral", nullable=false, length=45)
    public String getDataCompraRal() {
        return this.dataCompraRal;
    }
    
    public void setDataCompraRal(String dataCompraRal) {
        this.dataCompraRal = dataCompraRal;
    }

    
    @Column(name="total_ral", nullable=false)
    public int getTotalRal() {
        return this.totalRal;
    }
    
    public void setTotalRal(int totalRal) {
        this.totalRal = totalRal;
    }





}


