package bean;
// Generated 19/10/2023 12:07:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FuncionarioRal generated by hbm2java
 */
@Entity
@Table(name="funcionario_ral"
    ,catalog="db_rodrigo_ledesma"
)
public class FuncionarioRal  implements java.io.Serializable {


     private int idfuncionarioRal;
     private String nomeRal;
     private String cpfRal;
     private String emailRal;
     private String rgRal;
     

    public FuncionarioRal() {
    }

	
    public FuncionarioRal(int idfuncionarioRal, String nomeRal, String cpfRal, String emailRal, String rgRal) {
        this.idfuncionarioRal = idfuncionarioRal;
        this.nomeRal = nomeRal;
        this.cpfRal = cpfRal;
        this.emailRal = emailRal;
        this.rgRal = rgRal;
    }
    public FuncionarioRal(int idfuncionarioRal, String nomeRal, String cpfRal, String emailRal, String rgRal, Set compraRals) {
       this.idfuncionarioRal = idfuncionarioRal;
       this.nomeRal = nomeRal;
       this.cpfRal = cpfRal;
       this.emailRal = emailRal;
       this.rgRal = rgRal;
       
    }
   
     @Id 

    
    @Column(name="idfuncionario_ral", unique=true, nullable=false)
    public int getIdfuncionarioRal() {
        return this.idfuncionarioRal;
    }
    
    public void setIdfuncionarioRal(int idfuncionarioRal) {
        this.idfuncionarioRal = idfuncionarioRal;
    }

    
    @Column(name="nome_ral", nullable=false, length=45)
    public String getNomeRal() {
        return this.nomeRal;
    }
    
    public void setNomeRal(String nomeRal) {
        this.nomeRal = nomeRal;
    }

    
    @Column(name="cpf_ral", nullable=false, length=14)
    public String getCpfRal() {
        return this.cpfRal;
    }
    
    public void setCpfRal(String cpfRal) {
        this.cpfRal = cpfRal;
    }

    
    @Column(name="email_ral", nullable=false, length=80)
    public String getEmailRal() {
        return this.emailRal;
    }
    
    public void setEmailRal(String emailRal) {
        this.emailRal = emailRal;
    }

    
    @Column(name="rg_ral", nullable=false, length=15)
    public String getRgRal() {
        return this.rgRal;
    }
    
    public void setRgRal(String rgRal) {
        this.rgRal = rgRal;
    }






}


