package bean;
// Generated 14/09/2023 10:03:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoRal generated by hbm2java
 */
@Entity
@Table(name="produto_ral"
    ,catalog="db_rodrigo_ledesma"
)
public class ProdutoRal  implements java.io.Serializable {


     private int idprodutoRal;
     private String nomeRal;
     private int quantidadeRal;
     private String descricaoRal;
     private String tamanhoRal;
     private String precoRal;
     private String estoqueRal;
     

    public ProdutoRal() {
    }

	
    public ProdutoRal(int idprodutoRal, String nomeRal, int quantidadeRal, String descricaoRal, String tamanhoRal, String precoRal, String estoqueRal) {
        this.idprodutoRal = idprodutoRal;
        this.nomeRal = nomeRal;
        this.quantidadeRal = quantidadeRal;
        this.descricaoRal = descricaoRal;
        this.tamanhoRal = tamanhoRal;
        this.precoRal = precoRal;
        this.estoqueRal = estoqueRal;
    }
   
   
     @Id 

    
    @Column(name="idproduto_ral", unique=true, nullable=false)
    public int getIdprodutoRal() {
        return this.idprodutoRal;
    }
    
    public void setIdprodutoRal(int idprodutoRal) {
        this.idprodutoRal = idprodutoRal;
    }

    
    @Column(name="nome_ral", nullable=false, length=45)
    public String getNomeRal() {
        return this.nomeRal;
    }
    
    public void setNomeRal(String nomeRal) {
        this.nomeRal = nomeRal;
    }

    
    @Column(name="quantidade_ral", nullable=false)
    public int getQuantidadeRal() {
        return this.quantidadeRal;
    }
    
    public void setQuantidadeRal(int quantidadeRal) {
        this.quantidadeRal = quantidadeRal;
    }

    
    @Column(name="descricao_ral", nullable=false, length=250)
    public String getDescricaoRal() {
        return this.descricaoRal;
    }
    
    public void setDescricaoRal(String descricaoRal) {
        this.descricaoRal = descricaoRal;
    }

    
    @Column(name="tamanho_ral", nullable=false, length=45)
    public String getTamanhoRal() {
        return this.tamanhoRal;
    }
    
    public void setTamanhoRal(String tamanhoRal) {
        this.tamanhoRal = tamanhoRal;
    }

    
    @Column(name="preco_ral", nullable=false, length=45)
    public String getPrecoRal() {
        return this.precoRal;
    }
    
    public void setPrecoRal(String precoRal) {
        this.precoRal = precoRal;
    }

    
    @Column(name="estoque_ral", nullable=false, length=45)
    public String getEstoqueRal() {
        return this.estoqueRal;
    }
    
    public void setEstoqueRal(String estoqueRal) {
        this.estoqueRal = estoqueRal;
    }




}


